### ISSUE TITLE
2020-04-21 -- Experience report

### ISSUE THREAD

**Issue by matthewhammer** [dfinity/vessel#2]
This is not an _issue_ (or bug), so much as a short report of my recent experience using Vessel, as a Motoko programmer trying to separate a large repo into several smaller ones.

Overall: This tool is great.  It's doing exactly what I want and need.

Pros:
-----
- Vessel fills a niche that I needed: I want to have small Motoko repos that have interpendencies
- The "work" goes into a simple, re-usable form (the JSON entries in the `.vessel.json` and `.package-set.json` files)
- In about an hour, I was able to complete my refactoring task; hurray!
- `vessel verify` is awesome.  So calming. : )

Cons:
-----
- Moderate confusion: `vessel install` does not actually overwrite (re-install); It didn't propagate a fix that I thought it would.  I "worked around" this (intended?) behavior by deleting the `.vessel` subdir and repeating the `install` step again.
- Minor confusion: If one forgets to add a dependency that is present in the `.package-set.json` file, but absent from the dependencies list in `.vessel.json`, the compiler will give an unhelpful error that says that the package is unknown; vessel could help by suggesting the fix of copying the missing package name into the `.vessel.json` file.  But Vessel is simple, and doing that would be somewhat sophisticated (as would processing any errors from the compiler).

**Comment by matthewhammer** [comment]
Update: https://github.com/dfinity/motoko-bigmap/pull/16#issuecomment-647786708

Repeated here:
>   if I could do vessel sources [--package name path]* and optionally add extra entries of --package name/path pairs, that would be perfect.

These flags would permit me to better use `vessel` with ordinary local directories that provide one or more packages for a build.  The use case above would use the dfx cache for `base`, and `vessel` for other non-base repos.

In another design, the tool wrapping `vessel` could do this package-set combination, but given how things work today, that's not likely to be easier than just doing the combination here, in "`vessel`land", at least in the short term.

**Comment by matthewhammer** [comment]
Added this issue, for further discussion: https://github.com/kritzcreek/vessel/issues/6

**Comment by kritzcreek** [comment]
I think most of the feedback here was adressed/incorporated so I'm going to close this issue. Thanks for the detailed report!
