### ISSUE TITLE
escape branch name

### ISSUE THREAD

**Issue by chenyan-dfinity** [dfinity/vessel#22]
Trying to fetch base from branch `joachim/no-word`

```
{ name = "base"
        , repo = "https://github.com/dfinity/motoko-base"
        , version = "joachim/no-word"
        , dependencies = [] : List Text
        }
```

vessel install fails, maybe due to `/` in the branch name?

```
$ vessel install
[INFO] Installing 3 packages
[INFO] Downloading tar-ball: "base"
[WARN] Downloading tar-ball failed, cloning as git repo instead: "base"
Error: No such file or directory (os error 2)
```

**Comment by kritzcreek** [comment]
Yeah it's because of the slash. I'm thinking I'd prefer to improve the error message here instead and forbid slashes in `version`. You can always use a commit hash instead.

**Comment by rvanasa** [comment]
Closing since package names and versions are now restricted to letters, numbers, dashes, underscores, and the `.` character.
