### ISSUE TITLE
improve install instructions

### ISSUE THREAD

**Issue by electrovir** [dfinity/vessel#36]
The README currently states:

> 1. Download a copy of the vessel binary from the release page or build one yourself
> 2. Run vessel init in your project root.

There are a lot of steps missing in between 1 and 2. What do I do with the binary once I've downloaded it? Etc.

On macOS I had to `chmod +x` it, try to run it via `./vessel-macos`, open System Preferences > Security & Privacy and allow it to run, then I had to move it somewhere to it's in my path (I chose `/usr/local/bin` based on [this answer on StackExchange](https://superuser.com/a/7163)).

Issue #35 in here references a `vessel-install.sh` script, but I don't see that anywhere in this repo.

**Comment by nnsdaos** [comment]
@electrovir I think if it was a pkg file, it would be less harmful to newbies.

**Comment by ClankPan** [comment]
I tried these steps.

1. download the binary : "vessel-macos".
2. move it to "/usr/local"
3. run `chmod +x /usr/local/vessel-macos`
4. add `export PATH=$PATH:/usr/local/vessel-macos` & `alias vessel='vessel-macos'`

**Comment by fury02** [comment]
Hi
I ran into this problem myself. Yes, this is a barrier. I found it this way, maybe it will be useful to someone.
In dfx.json
```
 "defaults": {
    "build": {
      "args": "",
      "packtool": "vessel-linux64 sources"
    }
  },
```
 **"vessel-linux64 sources"**

**Comment by ArjaanBuijk** [comment]
This should work, just move it to `/usr/local/bin/vessel`.

That is already on the path, so no alias needed.

The exact steps:

```bash
# download the binary : "vessel-macos".

# Move it to /usr/local/bin/vessel
mv ~/Downloads/vessel-macos /usr/local/bin/vessel

# make it executable
chmod +x /usr/local/bin/vessel

# Test it. 
$ vessel --version
# The first time you run it, it  will be blocked, but you can unblock it...
# > Apple menu  > System Preferences, click Security & Privacy , then click General.
# (-) If the lock at the bottom left is locked , click it to unlock the preference pane.
# (-) Click on `open it anyways...`
```

**Comment by emenylouu** [comment]
> ```shell
> vessel --version
> ```

worked for me! Thanks.

**Comment by rvanasa** [comment]
Closing since the readme now contains more detailed installation instructions.
