### ISSUE TITLE
BUG: User reported crash

### ISSUE THREAD

**Issue by crusso** [dfinity/vessel#40]
No further repro info:

![unknown](https://user-images.githubusercontent.com/85788/149133755-f5ca6b45-a1d2-400a-8cab-f5959eb97607.png)

https://discordapp.com/channels/748416164832608337/748416164832608341/930766049903775754

**Comment by rvanasa** [comment]
This appears to be a one-off problem in which the GitHub API returned an empty array for the available vessel-package-set releases. 

Closing and will add a more detailed error message in case anyone encounters this situation in the future.
