### ISSUE TITLE
Problem on WSl2 (IC course ic-logger use vessel)

### ISSUE THREAD

**Issue by dragon-raja** [dfinity/vessel#46]
when I try to dfx build --check my project
It happens like that follows

Building canisters to check they build ok. Canister IDs might be hard coded.
Building canisters...
The build step failed for canister 'cs7ap-qc5fi-rjs6g-k5hmq' with an embedded error: The command '"vessel" "sources"' failed with exit status 'exit status: 101'.
Stdout:

Stderr:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("github.com")), port: None, path: "/dfinity/vessel-package-set/releases/download/mo-0.6.18-20220107/package-set.dhall", query: None, fragment: None }, source: TimedOut }', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/dhall-0.10.1/src/semantics/resolve/resolve.rs:295:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ggreif** [comment]
I suspect you have connectivity problems.

Please check if this works for you:
```
curl -L https://github.com/dfinity/vessel-package-set/releases/download/mo-0.6.18-20220107/package-set.dhall
```
It does for me...

**Comment by dragon-raja** [comment]
I ran the command line u gave
It seems like to work well hh
and it prints like that
could u give me some advice to solve the problem


[ { dependencies = [] : List Text
&nbsp; , name = "base"
&nbsp; , repo = "https://github.com/dfinity/motoko-base.git"
&nbsp; , version = "be85b15dc9fb45b3f24d83fccd2b24c3d19bc57d"
&nbsp; }
, { dependencies = [ "base" ]
&nbsp; , name = "crud"
&nbsp; , repo = "https://github.com/matthewhammer/motoko-crud.git"
&nbsp; , version = "c9bc6acbb6da81fc20d8ffec8063d9f6b4d01efd"
&nbsp; }
, { dependencies = [ "base" ]
&nbsp; , name = "matchers"
&nbsp; , repo = "https://github.com/kritzcreek/motoko-matchers.git"
&nbsp; , version = "v1.2.0"
&nbsp; }
, { dependencies = [ "base" ]
&nbsp; , name = "parsec"
&nbsp; , repo = "https://github.com/crusso/mo-parsec.git"
&nbsp; , version = "v1.0.0"
&nbsp; }
, { dependencies = [ "base" ]
&nbsp; , name = "scc"
&nbsp; , repo = "https://github.com/nomeata/motoko-scc.git"
&nbsp; , version = "v0.1"
&nbsp; }
, { dependencies = [ "base" ]
&nbsp; , name = "sha256"
&nbsp; , repo = "https://github.com/enzoh/motoko-sha.git"
&nbsp; , version = "9e2468f51ef060ae04fde8d573183191bda30189"
&nbsp; }
, { dependencies = [ "base" ]
&nbsp; , name = "icip"
&nbsp; , repo = "https://github.com/feliciss/icip.git"
&nbsp; , version = "v1.2.0"
&nbsp; }
, { dependencies = [ "base" ]
&nbsp; , name = "pretty"
&nbsp; , repo = "https://github.com/kritzcreek/motoko-pretty.git"
&nbsp; , version = "v0.1.0"
&nbsp; }
, { dependencies = [ "base" ]
&nbsp; , name = "sha224"
&nbsp; , repo = "https://github.com/flyq/motoko-sha224.git"
&nbsp; , version = "v0.1.0"
&nbsp; }
, { dependencies = [ "base" ]
&nbsp; , name = "splay"
&nbsp; , repo = "https://github.com/chenyan2002/motoko-splay.git"
&nbsp; , version = "v0.1.0"
&nbsp; }
, { dependencies = [ "base" ]
&nbsp; , name = "sequence"
&nbsp; , repo = "https://github.com/matthewhammer/motoko-sequence.git"
&nbsp; , version = "v0.1.1"
&nbsp; }
, { dependencies = [ "base" ]
&nbsp; , name = "base32"
&nbsp; , repo = "https://github.com/flyq/motoko-base32.git"
&nbsp; , version = "v0.1.1"
&nbsp; }
, { dependencies = [ "base" ]
&nbsp; , name = "adapton"
&nbsp; , repo = "https://github.com/matthewhammer/motoko-adapton.git"
&nbsp; , version = "v0.1.1"
&nbsp; }
]



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dfinity/vessel"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月8日(星期二) 上午6:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dfinity/vessel] Problem on WSl2 (IC course ic-logger use vessel) (Issue #46)





 
I suspect you have connectivity problems.
 
Please check if this works for you:
 curl -L https://github.com/dfinity/vessel-package-set/releases/download/mo-0.6.18-20220107/package-set.dhall  
It does for me...

**Comment by ggreif** [comment]
If the problem with `vessel` persists (connection keeps timing out while `curl` works just fine) them I'd try to upgrade `vessel` to the latest release. I am not a `vessel` dev, just suggesting the obvious.

**Comment by dragon-raja** [comment]
OK, thanks for your advice, but unfortunately the vessel is the latest release




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Gabor ***@***.***&gt;; 
发送时间: 2022年3月8日(星期二) 晚上6:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dfinity/vessel] Problem on WSl2 (IC course ic-logger use vessel) (Issue #46)





 
If the problem with vessel persists (connection keeps timing out while curl works just fine) them I'd try to upgrade vessel to the latest release. I am not a vessel dev, just suggesting the obvious.

**Comment by dragon-raja** [comment]
Finally, thanks for the answer, I finally solved the problem by configuring the windows system proxy for wsl2

**Comment by ggreif** [comment]
Looks like this is resolved now.
