### ISSUE TITLE
Using vessel with motoko base lib as a package and dfx 0.10.1 throws errors.

### ISSUE THREAD

**Issue by cristianbuta** [dfinity/vessel#53]
This is a followup on the issues discussed here https://github.com/dfinity/motoko-base/issues/397 and here https://github.com/dfinity/motoko-base/issues/392.

Using master as the latest branch for motoko base lib(current commit 25831e6e03c0231a2839029f048e10f61a2dcb03) throws an error saying: `Text.mo:83 type error [M0072], field textCompare does not exist in type`. Reverting the changes in sources that are mentioned in this commit https://github.com/dfinity/motoko-base/commit/c5071050e2c142b683329d712059a9ef142add8e throws another error saying `.vessel/base/master/src/ExperimentalStableMemory.mo:64.5-64.9: type error [M0072], field stableVarQuery does not exist in type`.

Tested on:
vessel v0.6.4 and v0.6.3
dfx version 0.10.1
system: ubuntu 20.04

**Comment by rvanasa** [comment]
Closing since this should be fixed in recent versions. Please let me know if you continue running into this on the latest Vessel release ([0.6.5](https://github.com/dfinity/vessel/releases/tag/v0.6.5)) and I will reopen this issue.
