### ISSUE TITLE
error while loading shared libraries: `libssl.so.1.1`

### ISSUE THREAD

**Issue by AndreLeifert** [dfinity/vessel#77]
this, TOO, doesn't work as it should:
> vessel init
> vessel: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

what if I have openssl-3.1.4-1 installed?

**Comment by ggreif** [comment]
This is a common problem in the Linux world. Which version of `vessel` did you download? (The newest is 0.7.0).

**Comment by ggreif** [comment]
NB.: #80 updates the README.

**Comment by AndreLeifert** [comment]
Well, that was quick - chapeau!
0.7.0 works for me (of course I followed the link in README).
Thanks, gentlemen.

**Comment by ggreif** [comment]
> Thanks, gentlemen.

You're welcome! Glad it did work out :-)
